version: "3.1"
services: 
    nexus:
        image: sonatype/nexus3:3.20.1
        container_name: nexus3
        restart: always
        ports: 
            - 8081:8081
        volumes: 
            - ./data:/nexus-data