# https://nginxproxymanager.com/guide/
version: "3.8"
services:
  app:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
      - "8401:8401" # 自定义其他 server 监听的端口，页面上通过 stream 添加
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
