version: "3.1"
services:
  ck-node-1:
    container_name: ck-node-1
    image: clickhouse/clickhouse-server
    restart: always
    hostname: ck-node-1
    env_file:
     - .env
    expose:
      - 9000
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - ${PWD}/data:/var/lib/clickhouse
      - ${PWD}/log:/var/log/clickhouse-server
      - ${PWD}/config:/etc/clickhouse-server