version: v3
services: 
  etcd:
    image: quay.io/coreos/etcd:v3.4.13
    container_name: etcd-single
    command: etcd -name etcd0 --data-dir=/etcd-data -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:2380
    volumes:
      - ./data:/etcd-data
    ports:
     - 12379:2379
     - 12380:2380
    networks:
     - etcd_single
    restart: on-failure
    environment:
      ALLOW_NONE_AUTHENTICATION: yes
      ETCD_AUTO_COMPACTION_MODE: revision
      ETCD_AUTO_COMPACTION_RETENTION: 1000
      ETCD_QUOTA_BACKEND_BYTES: 4294967296 # 4G 数据库文件的最大体积限制
      ETCD_SNAPSHOT_COUNT: 50000 # 快照频率 。每处理 50,000 个事务（写操作）就触发一次快照存盘。这有助于加快重启恢复速度并控制日志文件大小
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3
  etcdkeeper:
    image: deltaprojects/etcdkeeper
    container_name: etcdkeeper-single
    ports:
     - 8080:8080
    networks:
     - etcd_single
networks:
  etcd_single:
    driver: bridge
  