version: "3"
services:
  redis:
    image: redis:5.0.5
    container_name: redis5
    restart: always
    ports:
      - "6379:6379"
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ${PWD}/redis.conf:/etc/redis/redis.conf
      - ${PWD}/data:/data
    command: redis-server /etc/redis/redis.conf
    networks:
      - redisnet
networks:
  redisnet:
    driver: bridge
