version: "3.1"
services:
  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    restart: always
    volumes:
      - ${PWD}/data:/opt/sonarqube/data
      - ${PWD}/logs:/opt/sonarqube/logs
      - ${PWD}/extensions:/opt/sonarqube/extensions
    ports:
      - 9008:9000

   