version: "3.7"
x-project-base:
  &project-base
  restart: always
  networks:
    - remixide

networks:
  remixide:

services:
  remixide:
    <<: *project-base
    image: remixproject/remix-ide
    container_name: remixide
    ports: 
      - 8881:80
      - 65520:65520
