version: "3"
services:
  redis:
    image: redis:6.0
    container_name: single-redis6
    restart: always
    ports:
      - "6380:6379"
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ${PWD}/redis.conf:/etc/redis/redis.conf
      - ${PWD}/data:/data
    command: redis-server /etc/redis/redis.conf
    networks:
      - redisnet
networks:
  redisnet:
    driver: bridge
