version: "3.1"
services:
  goproxy:
    image: goproxy/goproxy
    container_name: goproxy
    restart: always
    environment:
     - "http_proxy=192.168.120.53:8080"
     - "https_proxy=192.168.120.53:8080"
    volumes:
      - ./data/cache:/go
    ports:
      - 8888:8081
    command: "-listen=0.0.0.0:8081 -cacheDir=/go -proxy https://goproxy.io -exclude 'goproxy.iyi.com'"