version: "3.1"
services:
    rabbitmq:
        image: rabbitmq:3.11-management
        restart: always
        container_name: RabbitMQ3.11
        environment:
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: 123456
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ${PWD}/data:/var/lib/rabbitmq

