version: "3.1"
services:
    rabbitmq:
        image: rabbitmq:3.8.2-management
        restart: always
        container_name: RabbitMQ3.8.2
        environment:
            RABBITMQ_DEFAULT_USER: test
            RABBITMQ_DEFAULT_PASS: 123456
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - /root/rabbitmq/home:/var/lib/rabbitmq

