version: "3.1"
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    restart: always
    container_name: RabbitMQ3.11
    env_file:
      - ./.env
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ${PWD}/data:/var/lib/rabbitmq
      - ${PWD}/log:/var/log/rabbitmq
      - ${PWD}/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
