version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ce:13.12.7-ce.0'
    restart: always
    platform: linux/amd64
    container_name: gitlab
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:9525'
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - '9525:80'
      - '9443:443'
      - '9022:22'
    volumes:
      - '/Users/wenjunjiang/work/yw/cn/gitlab-data2/config:/etc/gitlab'
      - '/Users/wenjunjiang/work/yw/cn/gitlab-data2/logs:/var/log/gitlab'
      - '/Users/wenjunjiang/work/yw/cn/gitlab-data2/data:/var/opt/gitlab'
    shm_size: '256m'