version: "3.1"
services:
  mongoReplica1:
    image: mongo:4.2.8
    container_name: mongoReplica1
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 28017:28017
    volumes:
      - ./data/db1/logs/:/data/db/mongo.log
      - ./data/db1:/data/db
      - ./mongod1.conf:/etc/mongod.conf
    command: --config /etc/mongod.conf
  mongoReplica2:
    image: mongo:4.2.8
    container_name: mongoReplica2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 28018:28018
    volumes:
      - ./data/db2/logs/:/data/db/mongo.log
      - ./data/db2:/data/db
      - ./mongod2.conf:/etc/mongod.conf
    command: --config /etc/mongod.conf
  mongoReplica3:
    image: mongo:4.2.8
    container_name: mongoReplica3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 28019:28017
    volumes:
      - ./data/db3/logs/:/data/db/mongo.log
      - ./data/db3:/data/db
      - ./mongod3.conf:/etc/mongod.conf
    command: --config /etc/mongod.conf
