version: "3.1"
services:
  mongo:
    image: mongo:4.2.8
    container_name: mongoSingleServer
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - ./single/data:/data/db
      - ./single/mongodb.key:/data/mongodb.key
