version: "3.1"
services: 
    elasticsearch:
        image: elasticsearch:7.6.1
        container_name: es01
        environment: 
            - node.name=es01
            - cluster.name=es-docker-cluster
            - discover.seed_hosts=es02,es03
            - cluster.initial_master_nodes=es01,es02,es03
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits: 
            memlock:
                soft: -1
                hard: -1
        volumes: 
            - data01:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks: 
            - elastic
    elasticsearch02:
        image: elasticsearch:7.6.1
        container_name: es02
        environment: 
            - node.name=es02
            - cluster.name=es-docker-cluster
            - discover.seed_hosts=es01,es03
            - cluster.initial_master_nodes=es01,es02,es03
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits: 
            memlock:
                soft: -1
                hard: -1
        volumes: 
            - data02:/usr/share/elasticsearch/data
        networks: 
            - elastic
    elasticsearch03:
        image: elasticsearch:7.6.1
        container_name: es03
        environment: 
            - node.name=es03
            - cluster.name=es-docker-cluster
            - discover.seed_hosts=es01,es02
            - cluster.initial_master_nodes=es01,es02,es03
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits: 
            memlock:
                soft: -1
                hard: -1
        volumes: 
            - data03:/usr/share/elasticsearch/data
        networks: 
            - elastic
    kibana:
        image: kibana:7.6.1
        container_name: kibana
        environment: 
            - I18N_LOCAL=zh-CN
        ports:
            - 5601:5601
        networks:
            - elastic
    cerebro:
        image: lmenezes/cerebro
        container_name: cerebro
        ports: 
            - 9000:9000
        networks: 
            - elastic
        command: 
            - -Dhosts.0.host=http://es01:9200
volumes: 
    data01:
        driver: local
    data02:
        driver: local
    data03:
        driver: local

networks: 
    elastic:
        driver: bridge