version: "3.8"
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.12.2
    environment:
      - discovery.type=single-node
      - TZ=Asia/Shanghai
    ports:
      - "9200:9200"
      - "9300:9300"
    mem_limit: 1g
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./data:/usr/share/elasticsearch/data
      - ./plugins:/usr/share/elasticsearch/plugins
    networks:
      - elastic

  kibana:
    container_name: kibana
    image: kibana:8.12.2
    ports:
      - "5601:5601"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch
    networks:
      - elastic

networks:
  elastic:
    external: true
