version: '3'
services:
  ql-dev:
    image: golang:1.17-bullseye
    container_name: golang-1.17-bullseye
    restart: always
    volumes:
      - /Users/wenjunjiang/work/ql:/home/ql
      - /Users/wenjunjiang/work/xy:/home/xy
    networks:
      - host
    entrypoint: ["/bin/bash"]
networks:
  host: