version: "3.0"
services:
  certimate:
    image: registry.cn-shanghai.aliyuncs.com/usual2970/certimate:latest
    container_name: certimate_server
    ports:
      - 8090:8090 #默认用户名和密码：用户名：admin@certimate.fun 密码：1234567890
    volumes:
      - ./data:/app/pb_data
    restart: unless-stopped