version: '3'
services: 
    nginx:
        image: nginx:stable
        container_name: nginx-stable
        restart: always
        ports: 
            - 80:80
            - 443:443
        volumes: 
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./conf.d/:/etc/nginx/conf.d/