version: "3.1"
services:
    mysql:
        image: mysql:8.0
        # platform: linux/amd64 # mac M1 linux/amd64
        container_name: mysql8.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123456
        volumes: # 该路径根据实际修改
            - ${PWD}/data8.0/data:/var/lib/mysql
            - ${PWD}/data8.0/logs:/var/log/mysql
            - ${PWD}/data8.0/mysql-files:/var/lib/mysql-files
            - ${PWD}/conf:/etc/mysql/conf.d
        ports:
            - 3307:3306