version: "3.1"
services:
    mysql:
        image: mysql:5.7.29
        platform: linux/amd64 # mac M1 linux/amd64
        container_name: mysql5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123456
        volumes: # 该路径根据实际修改
            - ${PWD}/data5.7/data:/var/lib/mysql
            - ${PWD}/data5.7/mysql-files:/var/lib/mysql-files
            - ${PWD}/data5.7/logs:/var/log/mysql
            - ${PWD}/mysql/conf:/etc/mysql/conf.d
        ports:
            - 3306:3306
networks:
  redisnet:
    driver: bridge