version: "3.1"
services: 
    yapi:
        image: .
        container_name: YapiServer
    mongo: 
        image: mongo:4.0
        container_name: mongoServer
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        ports:
            - 27017:27017
        volumes: 
            - ./mongo/data:/data/db