version: "3"

services:
  postgres:
    image: postgres:12
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
      PGDAT: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/var/lib/postgresql/data
